#!/bin/bash

curl -ss https://raw.githubusercontent.com/rubyonracetracks/docker-debian-stretch-build/master/rails-general/usr_local_bin/check-rails-general | bash

echo '#################################'
echo 'BEGIN rails-rubymn2 sanity checks'
echo '#################################'

echo 'No additional sanity checks'

echo '####################################'
echo 'FINISHED rails-rubymn2 sanity checks'
echo '####################################'
