#!/bin/bash

T_BEGIN=$(date +'%s')

echo '--------------------'
echo 'ls -l /usr/local/bin'
ls -l /usr/local/bin

# Prepare apt-get
/usr/local/bin/aptget

# Set environment variables to cut down on annoying warning messages
export DEBIAN_FRONTEND='noninteractive'
export DEBCONF_NOWARNINGS='true'
export HOME=/root
export LC_ALL=C

echo '####################################'
echo 'BEGIN rails-sessionizer-root actions'
echo '####################################'

echo '++++++++++++++++++++++++++++++++++++++++++++'
echo 'BEGIN installing prerequisites for PhantomJS'

# From https://github.com/OpenTwinCities/adopt-a-tree
# and https://gist.github.com/julionc/7476620

echo '---------------------------------------------------------------------------'
echo 'apt-get install -y libffi-dev build-essential chrpath libssl-dev libxft-dev'
apt-get install -y libffi-dev build-essential chrpath libssl-dev libxft-dev

echo '----------------------------------------------------------------------------------'
echo 'apt-get install -y libfreetype6 libfreetype6-dev libfontconfig1 libfontconfig1-dev'
apt-get install -y libfreetype6 libfreetype6-dev libfontconfig1 libfontconfig1-dev

echo 'FINISHED installing prerequisites for PhantomJS'
echo '+++++++++++++++++++++++++++++++++++++++++++++++'

echo '#######################################'
echo 'FINISHED rails-sessionizer-root actions'
echo '#######################################'

su -c /usr/local/bin/rails-sessionizer-user1 winner
su -c /usr/local/bin/rails-sessionizer-user2 winner
/usr/local/bin/finalize-root
su -c /usr/local/bin/finalize-user winner
su -c /usr/local/bin/check-rails-sessionizer winner

T_FINISH=$(date +'%s')
T_ELAPSED=$(($T_FINISH-$T_BEGIN))
echo '-----------------------------------------------------------------'
echo 'Time to transform the dev image into the rails-sessionizer image:'
echo "$(($T_ELAPSED / 60)) minutes and $(($T_ELAPSED % 60)) seconds"

